In [163]:
import numpy as np
import pandas as pd
import data_als
import data_prepro

In [164]:
train,test = data_prepro.loadData('datasets/data_tr_city.csv','datasets/data_ts_city.csv')

In [165]:
train = data_prepro.outlierDataToNan(train)
test = data_prepro.outlierDataToNan(test)

In [166]:
train = data_prepro.fillnaBehind(train)
test = data_prepro.fillnaBehind(test)

Int64Index([ 1748,  1982,  2127,  3468,  3485,  3491,  3513,  3533,  3542,
             3554,  3593,  3607, 10208, 11995, 12519, 12716, 12717, 13187,
            13234, 17558, 26078, 26079, 27253, 27254],
           dtype='int64')
datetime               0
구미 혁신도시배수지 유출유량 적산차    0
year                   0
month                  0
dtype: int64
Int64Index([1502], dtype='int64')
datetime               0
구미 혁신도시배수지 유출유량 적산차    0
year                   0
month                  0
dtype: int64


In [167]:
df = train

In [168]:
df['구미 혁신도시배수지 유출유량 적산차'].to_numpy()

array([138., 237., 128., ..., 335., 141., 112.])

In [169]:
X,Y = data_prepro.XDataToXAndYSeq(df)

In [170]:
X_test,Y_test = data_prepro.XDataToXAndYSeq(test)

In [171]:
Y.shape

(35038, 1)

In [172]:
Y

array([[113.],
       [ 51.],
       [ 10.],
       ...,
       [335.],
       [141.],
       [112.]])

In [173]:
X.shape

(35038, 24)

In [174]:
X

array([[138., 237., 128., ..., 152., 197., 175.],
       [237., 128.,  14., ..., 197., 175., 266.],
       [128.,  14.,  11., ..., 175., 266., 113.],
       ...,
       [305., 362., 207., ..., 473., 305., 328.],
       [362., 207., 133., ..., 305., 328., 347.],
       [207., 133., 153., ..., 328., 347., 335.]])

In [175]:
X = X.reshape((-1,24,1))

In [176]:
from tensorflow import keras

In [177]:
model = keras.Sequential()

model.add(keras.layers.GRU(256,X,input_shape=(24,1),return_sequences=True))
model.add(keras.layers.GRU(256,return_sequences=True))
model.add(keras.layers.GRU(256,return_sequences=True))
model.add(keras.layers.Dense(1024))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(1))

TypeError: Could not interpret activation function identifier: [[[138.]
  [237.]
  [128.]
  ...
  [152.]
  [197.]
  [175.]]

 [[237.]
  [128.]
  [ 14.]
  ...
  [197.]
  [175.]
  [266.]]

 [[128.]
  [ 14.]
  [ 11.]
  ...
  [175.]
  [266.]
  [113.]]

 ...

 [[305.]
  [362.]
  [207.]
  ...
  [473.]
  [305.]
  [328.]]

 [[362.]
  [207.]
  [133.]
  ...
  [305.]
  [328.]
  [347.]]

 [[207.]
  [133.]
  [153.]
  ...
  [328.]
  [347.]
  [335.]]]