In [45]:
import numpy as np
import pandas as pd
import data_als
import data_prepro

In [46]:
train,test = data_prepro.loadData('datasets/data_tr_city.csv','datasets/data_ts_city.csv')

In [47]:
train = data_prepro.outlierDataToNan(train)
test = data_prepro.outlierDataToNan(test)

In [48]:
train = data_prepro.fillnaBehind(train)
test = data_prepro.fillnaBehind(test)

Index([ 1748,  1982,  2127,  3468,  3485,  3491,  3513,  3533,  3542,  3554,
        3593,  3607, 10208, 11995, 12519, 12716, 12717, 13187, 13234, 17558,
       26078, 26079, 27253, 27254],
      dtype='int64')
datetime               0
구미 혁신도시배수지 유출유량 적산차    0
year                   0
month                  0
dtype: int64
Index([1502], dtype='int64')
datetime               0
구미 혁신도시배수지 유출유량 적산차    0
year                   0
month                  0
dtype: int64


In [49]:
df = train

In [50]:
df['구미 혁신도시배수지 유출유량 적산차'].to_numpy()

array([138., 237., 128., ..., 335., 141., 112.])

In [51]:
X,Y = data_prepro.XDataToXAndYSeq(df)

In [52]:
X_test,Y_test = data_prepro.XDataToXAndYSeq(test)

In [53]:
Y.shape

(35038, 1)

In [54]:
Y

array([[113.],
       [ 51.],
       [ 10.],
       ...,
       [335.],
       [141.],
       [112.]])

In [55]:
X.shape

(35038, 24)

In [56]:
X

array([[138., 237., 128., ..., 152., 197., 175.],
       [237., 128.,  14., ..., 197., 175., 266.],
       [128.,  14.,  11., ..., 175., 266., 113.],
       ...,
       [305., 362., 207., ..., 473., 305., 328.],
       [362., 207., 133., ..., 305., 328., 347.],
       [207., 133., 153., ..., 328., 347., 335.]])

In [57]:
X = X.reshape((-1,24,1))

In [58]:
# import torch

In [59]:
# device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [60]:
# cuda = True if torch.cuda.is_available() else False
# Tensor = torch.cuda.FloatTensor if cuda else torch.FloatTensor

In [61]:
# import torch.nn as nn
# import torch.nn.functional as F

In [62]:
# class Net(nn.Module):
#     def __init__(self,num_classes,input_size,hidden_size,num_layers,seq_length):
#         self.num_classes = num_classes
#         self.num_layers = num_layers
#         self.input_size = input_size
#         self.hidden_size = hidden_size
#         self.seq_length = seq_length
        
#         self.conv = nn.Sequential(
#             nn.Flatten(),
#             nn.GRU()
#         )

In [63]:
# num_classes = 1
# input_size = 24
# hidden_size = 512
# num_layers = 


# model=GRU(num_classes,input_size,hidden_size,num_layers,X_train_tensors_f.shape[1])

In [64]:
from tensorflow import keras

In [65]:
model = keras.models.load_model('100epochs_CPU.h5')

In [66]:
model.evaluate(X_test,Y_test)

263/263 [==============================] - 27s 95ms/step - loss: 104.7026 - accuracy: 0.0000e+00


[104.70259094238281, 0.0]